### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by sol2014** [treveradams/openerp-freeswitch-connector#1]
I got this error while trying to install this module and was hoping you could provide some step-by-step instructions on how to resolve this? error while importing module 'openerp-freeswitch-connector-master" "depends"

I just discovered more about this issue. It appears it is dependent on an ESL module. The problem I am seeing is that I can't find any such module out that unless I install Freeswitch on the same server that Odoo is running on. I currently have FS on another server and Odoo on a separate one.

**Comment by treveradams** [comment]
I have updated some documentation. It should help solve this issue.

**Comment by treveradams** [comment]
https://pypi.python.org/pypi/FreeSWITCH-ESL-Python/1.2

pip install FreeSWITCH-ESL-Python

If that doesn't solve the problem, please let me know.
